global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'petclinic'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['petclinic:8081']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']