version: '3.8'

services:
  burpsuite-community:
    build:
      context: .
      dockerfile: Dockerfile
    image: burp-burpsuite-community
    container_name: burpsuite-community
    networks:
      - petclinic-devops-net

networks:
  petclinic-devops-net:
    external: true
